# notifications
exec_always --no-startup-id dunst 

# lock screen on suspend
exec_always --no-startup-id xss-lock -- i3lock -n

# load colors from Xresources
exec_always --no-startup-id sleep 1 && xrdb -merge ~/.Xresources

# blue light filter
exec_always --no-startup-id sh -c "killall gammastep; gammastep"

# auto-mount USB
exec_always --no-startup-id udiskie

# restore last wallpaper from cache
exec_always --no-startup-id ~/.config/i3/scripts/rofi-wallpaper --reset
