# colors from Xresources
set_from_resource $bg      i3wm.color0 #3b2a20
set_from_resource $fg      i3wm.color7 #f3e7dc
set_from_resource $primary i3wm.color1 #5a3a2a
set_from_resource $dark    i3wm.color8 #2a1c16
set_from_resource $urgent  i3wm.color9 #8a3b2a

bar {
    font pango:JetBrains Mono Regular 8
    status_command i3status-rs ~/.config/i3/i3status-rs/config.toml
    position bottom
    tray_output primary
    
    colors {
        background $bg
        statusline $fg
        separator  $dark

        #                  border   bg       text
        focused_workspace  $primary $primary $fg
        active_workspace   $dark    $dark    $fg
        inactive_workspace $bg      $bg      $dark
        urgent_workspace   $urgent  $urgent  $fg
    }
}
