# ====== SCREENSHOTS ======
# Print: fullscreen, $mod+Shift+s: region
bindsym Print exec --no-startup-id flameshot full -c
bindsym Mod4+Shift+s exec --no-startup-id flameshot gui

# ====== BROWSER ======
bindsym $mod+w exec firefox

# ====== ROFI ======
# $mod+d: app launcher, $mod+v: clipboard, $mod+Tab: window switcher, $mod+r: power menu
bindsym $mod+d exec rofi -show drun 
bindsym $mod+v exec rofi -modi "clipboard:greenclip print" -show clipboard
bindsym $mod+Tab exec --no-startup-id "rofi -show"
bindsym $mod+r exec --no-startup-id ~/.config/i3/scripts/powermenu.sh

# ====== WALLPAPER ======
bindsym $mod+a exec ~/.config/i3/scripts/rofi-wallpaper

