# ====== KEYBOARD ======
# disable key repeat delay
exec_always --no-startup-id xset r rate 200 50

# ====== BORDERS ======
default_border pixel 1
default_floating_border pixel 1
smart_borders no_gaps
hide_edge_borders none
for_window [class="^.*"] border pixel 1
for_window [class="(?i)firefox"] border none

# ====== PYWAL COLORS ======
set_from_resource $color0 i3wm.color0 #000000
set_from_resource $color1 i3wm.color1 #ff0000
set_from_resource $color2 i3wm.color2 #00ff00
set_from_resource $color3 i3wm.color3 #ffff00
set_from_resource $color4 i3wm.color4 #0000ff
set_from_resource $color5 i3wm.color5 #ff00ff
set_from_resource $color6 i3wm.color6 #00ffff
set_from_resource $color7 i3wm.color7 #ffffff
set_from_resource $color8 i3wm.color8 #808080
set_from_resource $color9 i3wm.color9 #ff5555
set_from_resource $color10 i3wm.color10 #55ff55
set_from_resource $color11 i3wm.color11 #ffff55
set_from_resource $color12 i3wm.color12 #5555ff
set_from_resource $color13 i3wm.color13 #ff55ff
set_from_resource $color14 i3wm.color14 #55ffff
set_from_resource $color15 i3wm.color15 #f0f0f0

# ====== WINDOW COLORS ======
# border  bg      text
client.focused          $color4 $color4 $color15 $color4 $color4
client.focused_inactive $color8 $color8 $color15 $color8 $color8
client.unfocused        $color0 $color0 $color8  $color0 $color0
client.urgent           $color1 $color1 $color15 $color1 $color1
client.placeholder      $color8 $color8 $color15 $color8 $color8
client.background       $color0
