Section "InputClass"
    Identifier      "touchpad"
    MatchIsTouchpad "on"
    Driver          "libinput"

    # Natural scrolling
    Option "NaturalScrolling" "on"

    # Tap-to-click
    Option "Tapping" "on"

    # Accel profile adaptive + speed
    Option "AccelProfile" "adaptive"
    Option "AccelSpeed"   "-0.39"
EndSection
