[theme]
theme = "native"

[icons]
icons = "awesome4"

[icons.overrides]
power-off = "\uf011"

[[block]]
block = "keyboard_layout"
driver = "xkbevent"
format = " ⌨  $layout "

[block.mappings]
"English (US)" = "EN"
"Russian (N/A)" = "RU"

[[block.click]]
button = "left"
cmd = "xdotool key alt+shift"
update = true

[[block]]
block = "backlight"
format = " $icon $brightness "

[[block]]
block = "sound"
format = " $icon { $volume|} "
show_volume_when_muted = true
driver = "auto"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:25) $prev $play $next |}"

[[block]]
block = "net"
interval = 5
format = " $icon "
format_alt = " $icon $speed_down.eng(prefix:K)↓ $speed_up.eng(prefix:K)↑ "
inactive_format = " $icon ✗ "
missing_format = " ✗ "
[[block.click]]
button = "right"
cmd = "i3-sensible-terminal -e nmtui"
update = false

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%R') "

[[block]]
block = "custom"
command = "echo '{\"icon\":\"power-off\",\"text\":\"\"}'"
json = true
interval = 86400
format = " $icon "
[[block.click]]
button = "left"
cmd = "~/.config/i3/scripts/powermenu.sh"
