# ====== FLOATING / TILING ======
# reset i3status after volume change
set $refresh_i3status killall -SIGUSR1 i3status

# drag floating windows with mouse + $mod
floating_modifier $mod

# drag tiling windows by title bar
tiling_drag modifier titlebar

# ====== WORKSPACES ======
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

